#
# Build the RNBO OSCQuery Runner Debian package.
#
FROM node:22-bookworm-slim AS build

ENV DEBIAN_FRONTEND=noninteractive
ENV FAKECHROOT=true
VOLUME /var/cache/apt/packages

# Cross-compilation options
# CPU for CMake and arch for Conan
ARG CPU=armv8
# CPU flags for compiler
ARG MCPU=-mcpu=cortex-a76
# Debian package architecture
ARG ARCH=arm64
# Toolchain prefix
ARG CHOST=aarch64-linux-gnu

# Toolchain
ENV AR=${CHOST}-ar
ENV AS=${CHOST}-as
ENV RANLIB=${CHOST}-ranlib
ENV CC=${CHOST}-gcc
ENV CXX=${CHOST}-g++
ENV STRIP=${CHOST}-strip
ENV RC=${CHOST}-windres
ENV CFLAGS="${MCPU} -O3"
ENV CXXFLAGS=${CFLAGS}
ENV ASFLAGS=${CFLAGS}

# Packages
RUN <<EOF
  # Add target architecture for library dependencies
  dpkg --add-architecture ${ARCH} && apt-get update

  # Install build tools and libraries
  apt-get -y --no-install-recommends install \
      ca-certificates curl make git \
      gcc g++ cmake gettext-base python3-pip \
      crossbuild-essential-${ARCH} \
      libavahi-compat-libdnssd-dev:${ARCH} \
      libssl-dev:${ARCH} libjack-jackd2-dev:${ARCH} \
      libxml2-dev:${ARCH} libsndfile1-dev:${ARCH}

  # Runner requires Conan 1.61
  pip3 install conan --break-system-packages conan==1.61.0
EOF

WORKDIR /build
VOLUME /root/.conan/data

# RNBO source version
ARG RNBO_SOURCE_VER=1.4.5

# rnbo.oscquery.runner tag, branch, or commit to build
ARG RNBO_RUNNER_REF=v1.4.5-10

# Fetch sources
RUN git init . && \
    git remote add origin https://github.com/Cycling74/rnbo.oscquery.runner.git && \
    git fetch --depth 1 origin "${RNBO_RUNNER_REF}" && \
    git checkout --detach FETCH_HEAD

# Add Cycling '74's repository to fetch RNBO sources
RUN <<EOF
  cp config/cycling74.list /etc/apt/sources.list.d/
  cp config/apt-cycling74-pubkey.asc /usr/share/keyrings/
EOF

# Add beta channel to allow building against beta versions of RNBO
RUN sed -E 's/^\s*(deb.*bookworm).*/\1 beta/g' config/cycling74.list > /etc/apt/sources.list.d/cycling74-beta.list

# Fetch pre-built rnbooscquery of the target version and extract to /opt
RUN <<EOF
  dpkg --add-architecture armhf && apt-get update
  apt-get download rnbooscquery=${RNBO_SOURCE_VER}
  dpkg-deb -X *.deb /opt && rm -f *.deb
EOF

# Create Conan profile from the template
RUN mkdir -p /root/.conan/profiles
RUN CHOST=$CHOST CC=$CC CXX=$CXX CPU=$CPU envsubst <<EOF > /root/.conan/profiles/default
  [buildenv]
  CHOST=$CHOST
  CC=$CC
  CXX=$CXX

  [settings]
  os=Linux
  arch=$CPU
  build_type=Release
  compiler=gcc
  compiler.version=12
  compiler.libcxx=libstdc++11
EOF

# Prepare CMake, which will fetch and build Conan dependencies too
RUN cmake \
      -DCMAKE_SYSTEM_PROCESSOR=${CPU} -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=${ARCH} \
      -DCMAKE_BUILD_TYPE=Release -DWITH_DBUS=Off -DRNBO_DIR=/opt/usr/src/rnbo .

# Build and create deb package
RUN cmake --build . && cpack

FROM scratch

COPY --from=build /build/*.deb /
