name: Build and Upload Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Debian packages
        run: |
          docker buildx build \
            --output type=local,dest=./output \
            --progress=plain .

      - name: List built files
        run: ls -lh output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages-${{ matrix.arch }}
          path: output/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: debian-packages-arm64
          path: output

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
